# GitHub Pages 配置
# 此文件用于配置 GitHub Pages 的部署设置

# 部署分支
branch: gh-pages

# 部署目录
path: /my-website/build

# 自定义域名（可选）
# cname: your-domain.com

# 启用 HTTPS
https_only: true

# 构建命令
build_command: cd my-website && npm run build

# 部署命令
deploy_command: cd my-website && npm run deploy 